# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'CampingDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NMapsMap'
  pod 'RxSwift', '~> 6.6.0'
  pod 'RxCocoa', '~> 6.6.0'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'RealmSwift', '~> 10.44.0'
  pod 'RxGesture', '~> 4.0.4'

  # Pods for CampingDiary

end
